version: '3.3'
services: 
  product-service:
    build:
      context: ./microservices-example/products
    ports:
      - "8000:3000"
    networks: 
      - microservices
  review-service:
    build:
      context: ./microservices-example/reviews
    ports:
      - "8001:3000"
    networks:
      - microservices
networks: 
  microservices: